### ISSUE TITLE
I can't show a new user on the screen.

### ISSUE THREAD

**Issue by Sebucha** [Sebucha/LocalStorage#3]
I added a function and I gave her a four new forms.  When I'm using console.log everything is okay with a "db" - added new user, but I can't show him  on the screen.

**Comment by Sebucha** [comment]
Now It's possible  add a new User but I don't think so it's the best solution.

**Comment by Sebucha** [comment]
I found a next problem. When I deleted a user(for example user{id:3} and later I wanna add new I dont have db withoud id:3 but  I have everygiht with new user. its not good.

**Comment by Lukortech** [comment]
> I found a next problem. When I deleted a user(for example user{id:3} and later I wanna add new I dont have db withoud id:3 but I have everygiht with new user. its not good.

https://github.com/Sebucha/LocalStorage/blob/608330258a7fa6ba7e5ee1372a1feb3ec33f7030/script.js#L99

Here lies the problem. 
You've deleted it from state in cache but then when you load the app you use the DB initially, right?
So it overwrites the data again (with initial state of DB). 

As we've discussed yesterday you need to take care of that first :)

**Comment by Lukortech** [comment]
> Now It's possible add a new User but I don't think so it's the best solution.

When commenting like that it's always good to reference a code part that's implementing said feature.
(especially that there's no PR)

**Comment by Sebucha** [comment]
> > I found a next problem. When I deleted a user(for example user{id:3} and later I wanna add new I dont have db withoud id:3 but I have everygiht with new user. its not good.
> 
> https://github.com/Sebucha/LocalStorage/blob/608330258a7fa6ba7e5ee1372a1feb3ec33f7030/script.js#L99
> 
> Here lies the problem. You've deleted it from state in cache but then when you load the app you use the DB initially, right? So it overwrites the data again (with initial state of DB).
> 
> As we've discussed yesterday you need to take care of that first :)

Okay, but still if I will change localStorage.removeItem(id) for localStorage.removeItem("APIdata") I will have the same problem. 
First I'm deleting everything but after clicked the button I have again everything with new  users.
